/**
 * Generated by `node scripts/build-hero-images.mjs`: do not edit by hand.
 *
 * These files were produced by Lens itself: downloaded at full size, then run
 * through `ImageOptimizer` with `LocalAdapter`. The numbers in `HERO_STATS`
 * are what that run measured, so the figure quoted on the landing page cannot
 * drift from what the library actually does.
 */

import type { StreamImage } from '@/components/ui/image-stream-hero';

export const HERO_IMAGES: StreamImage[] = [
  {
    "src": "/hero/hero-01.webp",
    "alt": "Lake reflecting a forested ridge at dusk"
  },
  {
    "src": "/hero/hero-02.webp",
    "alt": "Fog drifting through a stand of pines"
  },
  {
    "src": "/hero/hero-03.webp",
    "alt": "Aerial view of a coastline meeting open water"
  },
  {
    "src": "/hero/hero-04.webp",
    "alt": "Sunlight breaking through a dense forest canopy"
  },
  {
    "src": "/hero/hero-05.webp",
    "alt": "Snow-covered peaks above a still lake"
  },
  {
    "src": "/hero/hero-06.webp",
    "alt": "Green valley folding away into distant hills"
  },
  {
    "src": "/hero/hero-07.webp",
    "alt": "Narrow path winding between tall trees"
  },
  {
    "src": "/hero/hero-08.webp",
    "alt": "Low sun across an open field of grass"
  },
  {
    "src": "/hero/hero-09.webp",
    "alt": "Mountain ridge silhouetted against a bright sky"
  },
  {
    "src": "/hero/hero-10.webp",
    "alt": "Wooden cabin on the shore of a mountain lake"
  },
  {
    "src": "/hero/hero-11.webp",
    "alt": "Abstract sweep of pale rock and shadow"
  }
];

/** Measured across the whole set at build time. */
export const HERO_STATS = {
  "count": 11,
  "sourceBytes": 7593751,
  "outputBytes": 675654,
  "savingsPercent": 91
} as const;
