/**
 * Generated by `node scripts/build-hero-images.mjs`: do not edit by hand.
 *
 * Large, lightly compressed JPEGs for the playground to chew on. Served from
 * this origin so drawing them to a canvas does not taint it.
 */

export interface SampleImage {
  readonly name: string;
  readonly src: string;
  readonly alt: string;
  readonly bytes: number;
  readonly width: number;
  readonly height: number;
}

export const SAMPLE_IMAGES: SampleImage[] = [
  {
    "name": "Lake",
    "src": "/samples/lake.jpg",
    "alt": "Lake reflecting a forested ridge at dusk",
    "bytes": 553717,
    "width": 1800,
    "height": 1202
  },
  {
    "name": "Forest",
    "src": "/samples/forest.jpg",
    "alt": "Sunlight breaking through a dense forest canopy",
    "bytes": 986622,
    "width": 1800,
    "height": 1199
  },
  {
    "name": "Coast",
    "src": "/samples/coast.jpg",
    "alt": "Aerial view of a coastline meeting open water",
    "bytes": 1185183,
    "width": 1800,
    "height": 2700
  }
];
